"""add_authentication_foundation

Revision ID: 3295d9536783
Revises: 574d1e27cc56
Create Date: 2026-09-20 19:26:29.627639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3295d9536783'
down_revision: Union[str, None] = '574d1e27cc56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_refresh_token',
    sa.Column('refresh_token_id', sa.UUID(), nullable=False, comment='Unique identifier for the refresh token record (UUIDv4)'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Foreign key referencing user_master.user_id (ON DELETE CASCADE)'),
    sa.Column('jti', sa.String(length=64), nullable=False, comment='Unique JWT identifier (JTI) of the refresh token'),
    sa.Column('token_hash', sa.String(length=128), nullable=False, comment='Cryptographic SHA-256 hash of the issued refresh token (raw token is never stored)'),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the refresh token was issued (UTC)'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Expiration timestamp for the refresh token (UTC)'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the token was explicitly revoked/logged out/rotated (UTC)'),
    sa.Column('replaced_by_jti', sa.String(length=64), nullable=True, comment='JTI of the replacement refresh token upon rotation (for reuse detection)'),
    sa.Column('created_ip', sa.String(length=45), nullable=True, comment='Client IP address that requested the token'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='Client user agent string'),
    sa.ForeignKeyConstraint(['user_id'], ['user_master.user_id'], name='fk_refresh_token_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('refresh_token_id'),
    comment='Registry for hashed rotating refresh tokens and session revocation'
    )
    op.create_index(op.f('ix_auth_refresh_token_expires_at'), 'auth_refresh_token', ['expires_at'], unique=False)
    op.create_index(op.f('ix_auth_refresh_token_jti'), 'auth_refresh_token', ['jti'], unique=True)
    op.create_index(op.f('ix_auth_refresh_token_revoked_at'), 'auth_refresh_token', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_auth_refresh_token_token_hash'), 'auth_refresh_token', ['token_hash'], unique=False)
    op.create_index(op.f('ix_auth_refresh_token_user_id'), 'auth_refresh_token', ['user_id'], unique=False)
    op.add_column('user_master', sa.Column('password_hash', sa.String(length=255), nullable=True, comment='Argon2id password hash (nullable until user activates account)'))
    op.add_column('user_master', sa.Column('must_change_password', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Flag indicating if password change is required on next login'))
    op.add_column('user_master', sa.Column('failed_login_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='Counter for consecutive failed login attempts'))
    op.add_column('user_master', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True, comment='Timestamp until which account is locked due to failed login attempts'))
    op.add_column('user_master', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of most recent successful login (UTC)'))
    op.add_column('user_master', sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when password was last changed (UTC)'))
    op.add_column('user_master', sa.Column('token_version', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='Session token version for global revocation'))
    op.create_check_constraint('chk_user_failed_login_attempts_non_negative', 'user_master', 'failed_login_attempts >= 0')
    op.create_check_constraint('chk_user_token_version_positive', 'user_master', 'token_version > 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chk_user_token_version_positive', 'user_master', type_='check')
    op.drop_constraint('chk_user_failed_login_attempts_non_negative', 'user_master', type_='check')
    op.drop_column('user_master', 'token_version')
    op.drop_column('user_master', 'password_changed_at')
    op.drop_column('user_master', 'last_login_at')
    op.drop_column('user_master', 'locked_until')
    op.drop_column('user_master', 'failed_login_attempts')
    op.drop_column('user_master', 'must_change_password')
    op.drop_column('user_master', 'password_hash')
    op.drop_index(op.f('ix_auth_refresh_token_user_id'), table_name='auth_refresh_token')
    op.drop_index(op.f('ix_auth_refresh_token_token_hash'), table_name='auth_refresh_token')
    op.drop_index(op.f('ix_auth_refresh_token_revoked_at'), table_name='auth_refresh_token')
    op.drop_index(op.f('ix_auth_refresh_token_jti'), table_name='auth_refresh_token')
    op.drop_index(op.f('ix_auth_refresh_token_expires_at'), table_name='auth_refresh_token')
    op.drop_table('auth_refresh_token')
    # ### end Alembic commands ###
