"""create_department_master

Revision ID: 38b03f32afa9
Revises: b445258097c2
Create Date: 2026-09-20 16:01:30.811688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38b03f32afa9'
down_revision: Union[str, None] = 'b445258097c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department_master',
    sa.Column('department_id', sa.UUID(), nullable=False, comment='Unique identifier for the department (UUIDv4)'),
    sa.Column('company_id', sa.UUID(), nullable=False, comment='Foreign key referencing company_master.company_id (ON DELETE RESTRICT)'),
    sa.Column('department_code', sa.String(length=30), nullable=False, comment='Uppercase department code unique per company (e.g., ADMINISTRATION, SALES)'),
    sa.Column('department_name', sa.String(length=100), nullable=False, comment='Display name of the department (e.g., Administration, Sales, R&D)'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='Optional description of the department functions'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'ACTIVE'"), nullable=False, comment='Operational status: ACTIVE or INACTIVE'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when department record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when department record was last updated (UTC)'),
    sa.CheckConstraint("department_code ~ '^[A-Z_]+$'", name='chk_department_code_format'),
    sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE')", name='chk_department_status_valid'),
    sa.ForeignKeyConstraint(['company_id'], ['company_master.company_id'], name='fk_department_company_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('department_id'),
    sa.UniqueConstraint('company_id', 'department_code', name='uq_department_company_code'),
    sa.UniqueConstraint('company_id', 'department_name', name='uq_department_company_name'),
    comment='Master registry for company-specific departments in Gocompliances CRM'
    )
    op.create_index(op.f('ix_department_master_company_id'), 'department_master', ['company_id'], unique=False)
    op.create_index(op.f('ix_department_master_status'), 'department_master', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_department_master_status'), table_name='department_master')
    op.drop_index(op.f('ix_department_master_company_id'), table_name='department_master')
    op.drop_table('department_master')
    # ### end Alembic commands ###
