"""create_user_master

Revision ID: 574d1e27cc56
Revises: da18e31ab374
Create Date: 2026-09-20 16:52:25.550688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '574d1e27cc56'
down_revision: Union[str, None] = 'da18e31ab374'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_master',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Unique identifier for the user / employee (UUIDv4)'),
    sa.Column('employee_code', sa.String(length=20), nullable=False, comment='Globally unique uppercase employee code (e.g. CG0001, EP0001, BM0001)'),
    sa.Column('company_id', sa.UUID(), nullable=False, comment='Foreign key referencing company_master.company_id (ON DELETE RESTRICT)'),
    sa.Column('department_id', sa.UUID(), nullable=False, comment='Foreign key referencing department_master.department_id (ON DELETE RESTRICT)'),
    sa.Column('designation_id', sa.UUID(), nullable=False, comment='Foreign key referencing designation_master.designation_id (ON DELETE RESTRICT)'),
    sa.Column('manager_user_id', sa.UUID(), nullable=True, comment='Nullable self-referencing foreign key to reporting manager (ON DELETE SET NULL)'),
    sa.Column('first_name', sa.String(length=100), nullable=False, comment='Employee first name'),
    sa.Column('middle_name', sa.String(length=100), nullable=True, comment='Employee middle name (optional)'),
    sa.Column('last_name', sa.String(length=100), nullable=False, comment='Employee last name'),
    sa.Column('official_email', sa.String(length=255), nullable=False, comment='Official corporate email address (case-insensitively unique)'),
    sa.Column('personal_email', sa.String(length=255), nullable=True, comment='Personal email address (optional)'),
    sa.Column('mobile_number', sa.String(length=20), nullable=False, comment='Primary contact mobile number (e.g. +91XXXXXXXXXX)'),
    sa.Column('date_of_joining', sa.Date(), nullable=False, comment='Official date of joining'),
    sa.Column('employment_type', sa.String(length=20), nullable=False, comment='Employment type: FULL_TIME, PART_TIME, CONTRACT, INTERN, CONSULTANT'),
    sa.Column('account_status', sa.String(length=20), server_default=sa.text("'PENDING'"), nullable=False, comment='Account/employment status: PENDING, ACTIVE, INACTIVE, SUSPENDED'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when user record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when user record was last updated (UTC)'),
    sa.CheckConstraint("account_status IN ('PENDING', 'ACTIVE', 'INACTIVE', 'SUSPENDED')", name='chk_user_account_status_valid'),
    sa.CheckConstraint("employment_type IN ('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERN', 'CONSULTANT')", name='chk_user_employment_type_valid'),
    sa.CheckConstraint('manager_user_id IS NULL OR manager_user_id <> user_id', name='chk_user_self_manager'),
    sa.ForeignKeyConstraint(['company_id'], ['company_master.company_id'], name='fk_user_company_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['department_id'], ['department_master.department_id'], name='fk_user_department_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['designation_id'], ['designation_master.designation_id'], name='fk_user_designation_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['manager_user_id'], ['user_master.user_id'], name='fk_user_manager_user_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('user_id'),
    comment='Master registry for employees/users in Gocompliances CRM'
    )
    op.create_index(op.f('ix_user_master_account_status'), 'user_master', ['account_status'], unique=False)
    op.create_index(op.f('ix_user_master_company_id'), 'user_master', ['company_id'], unique=False)
    op.create_index(op.f('ix_user_master_department_id'), 'user_master', ['department_id'], unique=False)
    op.create_index(op.f('ix_user_master_designation_id'), 'user_master', ['designation_id'], unique=False)
    op.create_index(op.f('ix_user_master_employee_code'), 'user_master', ['employee_code'], unique=True)
    op.create_index(op.f('ix_user_master_manager_user_id'), 'user_master', ['manager_user_id'], unique=False)
    op.create_index('ix_user_master_official_email_lower', 'user_master', [sa.literal_column('lower(official_email)')], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_master_official_email_lower', table_name='user_master')
    op.drop_index(op.f('ix_user_master_manager_user_id'), table_name='user_master')
    op.drop_index(op.f('ix_user_master_employee_code'), table_name='user_master')
    op.drop_index(op.f('ix_user_master_designation_id'), table_name='user_master')
    op.drop_index(op.f('ix_user_master_department_id'), table_name='user_master')
    op.drop_index(op.f('ix_user_master_company_id'), table_name='user_master')
    op.drop_index(op.f('ix_user_master_account_status'), table_name='user_master')
    op.drop_table('user_master')
    # ### end Alembic commands ###
