"""create_user_module_permission

Revision ID: 65ff8484468e
Revises: f46f50205034
Create Date: 2026-09-20 19:56:59.365829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65ff8484468e'
down_revision: Union[str, None] = 'f46f50205034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_module_permission',
    sa.Column('permission_id', sa.UUID(), nullable=False, comment='Unique identifier for the permission grant (UUIDv4)'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Foreign key referencing target user (ON DELETE CASCADE)'),
    sa.Column('module_id', sa.UUID(), nullable=False, comment='Foreign key referencing target module (ON DELETE RESTRICT)'),
    sa.Column('can_view', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Permission to view module page and query records within data scope'),
    sa.Column('can_create', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Permission to create new records in module (requires can_view=true)'),
    sa.Column('can_edit', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Permission to edit records in module (requires can_view=true)'),
    sa.Column('can_delete', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Permission to delete/deactivate records in module (requires can_view=true)'),
    sa.Column('can_approve', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Permission to execute approval workflows in module (requires can_view=true)'),
    sa.Column('data_scope', sa.String(length=20), server_default=sa.text("'SELF'"), nullable=False, comment='Data visibility scope: SELF, TEAM, DEPARTMENT, COMPANY, ALL'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'ACTIVE'"), nullable=False, comment='Permission status: ACTIVE or INACTIVE'),
    sa.Column('granted_by_user_id', sa.UUID(), nullable=True, comment='Nullable foreign key to grantor user (ON DELETE SET NULL)'),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when permission was granted (UTC)'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='Optional expiration timestamp for temporary access (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when permission record was last updated (UTC)'),
    sa.CheckConstraint("data_scope IN ('SELF', 'TEAM', 'DEPARTMENT', 'COMPANY', 'ALL')", name='chk_permission_data_scope_valid'),
    sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE')", name='chk_permission_status_valid'),
    sa.CheckConstraint('can_view = true OR (can_create = false AND can_edit = false AND can_delete = false AND can_approve = false)', name='chk_permission_action_requires_view'),
    sa.CheckConstraint('expires_at IS NULL OR expires_at > granted_at', name='chk_permission_expires_after_granted'),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['user_master.user_id'], name='fk_permission_granted_by_user_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['module_id'], ['module_master.module_id'], name='fk_permission_module_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user_master.user_id'], name='fk_permission_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('permission_id'),
    sa.UniqueConstraint('user_id', 'module_id', name='uq_user_module_permission_user_module'),
    comment='Per-user granular permissions and data scope assignments for CRM modules'
    )
    op.create_index(op.f('ix_user_module_permission_expires_at'), 'user_module_permission', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_module_permission_granted_by_user_id'), 'user_module_permission', ['granted_by_user_id'], unique=False)
    op.create_index(op.f('ix_user_module_permission_module_id'), 'user_module_permission', ['module_id'], unique=False)
    op.create_index(op.f('ix_user_module_permission_status'), 'user_module_permission', ['status'], unique=False)
    op.create_index(op.f('ix_user_module_permission_user_id'), 'user_module_permission', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_module_permission_user_id'), table_name='user_module_permission')
    op.drop_index(op.f('ix_user_module_permission_status'), table_name='user_module_permission')
    op.drop_index(op.f('ix_user_module_permission_module_id'), table_name='user_module_permission')
    op.drop_index(op.f('ix_user_module_permission_granted_by_user_id'), table_name='user_module_permission')
    op.drop_index(op.f('ix_user_module_permission_expires_at'), table_name='user_module_permission')
    op.drop_table('user_module_permission')
    # ### end Alembic commands ###
