"""create_company_master

Revision ID: b445258097c2
Revises: f6d28a5264ee
Create Date: 2026-09-20 15:43:49.592309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b445258097c2'
down_revision: Union[str, None] = 'f6d28a5264ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_master',
    sa.Column('company_id', sa.UUID(), nullable=False, comment='Unique identifier for the company (UUIDv4)'),
    sa.Column('company_code', sa.String(length=20), nullable=False, comment='Unique uppercase business identifier code (e.g., GOCOMPLIANCES)'),
    sa.Column('company_name', sa.String(length=150), nullable=False, comment='Primary trade/display name of the company'),
    sa.Column('legal_name', sa.String(length=200), nullable=True, comment='Registered legal/corporate entity name (optional)'),
    sa.Column('employee_code_prefix', sa.String(length=5), nullable=False, comment='2-5 character uppercase prefix for employee IDs (e.g. CG, EP, BM)'),
    sa.Column('next_employee_number', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='Sequential counter for next employee code assignment (>0)'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'ACTIVE'"), nullable=False, comment='Operational status: ACTIVE or INACTIVE'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when company record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when company record was last updated (UTC)'),
    sa.CheckConstraint("employee_code_prefix ~ '^[A-Z]{2,5}$'", name='chk_company_employee_code_prefix_format'),
    sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE')", name='chk_company_status_valid'),
    sa.CheckConstraint('next_employee_number > 0', name='chk_company_next_employee_number_positive'),
    sa.PrimaryKeyConstraint('company_id'),
    sa.UniqueConstraint('employee_code_prefix'),
    comment='Master registry for companies operating within Gocompliances CRM'
    )
    op.create_index(op.f('ix_company_master_company_code'), 'company_master', ['company_code'], unique=True)
    op.create_index(op.f('ix_company_master_company_name'), 'company_master', ['company_name'], unique=True)
    op.create_index(op.f('ix_company_master_status'), 'company_master', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_master_status'), table_name='company_master')
    op.drop_index(op.f('ix_company_master_company_name'), table_name='company_master')
    op.drop_index(op.f('ix_company_master_company_code'), table_name='company_master')
    op.drop_table('company_master')
    # ### end Alembic commands ###
