"""create_designation_master

Revision ID: da18e31ab374
Revises: 38b03f32afa9
Create Date: 2026-09-20 16:37:09.981268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da18e31ab374'
down_revision: Union[str, None] = '38b03f32afa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('designation_master',
    sa.Column('designation_id', sa.UUID(), nullable=False, comment='Unique identifier for the designation (UUIDv4)'),
    sa.Column('company_id', sa.UUID(), nullable=False, comment='Foreign key referencing company_master.company_id (ON DELETE RESTRICT)'),
    sa.Column('designation_code', sa.String(length=50), nullable=False, comment='Uppercase designation code unique per company (e.g., EXECUTIVE, MANAGER)'),
    sa.Column('designation_name', sa.String(length=100), nullable=False, comment='Display job title of the designation (e.g., Executive, Manager, Director)'),
    sa.Column('level_rank', sa.Integer(), nullable=False, comment='Seniority level ranking counter (>0; higher value = higher seniority)'),
    sa.Column('is_managerial', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Classification flag indicating managerial position (informational only; does not grant permissions)'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='Optional description of the designation responsibilities'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'ACTIVE'"), nullable=False, comment='Operational status: ACTIVE or INACTIVE'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when designation record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when designation record was last updated (UTC)'),
    sa.CheckConstraint("designation_code ~ '^[A-Z_]+$'", name='chk_designation_code_format'),
    sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE')", name='chk_designation_status_valid'),
    sa.CheckConstraint('level_rank > 0', name='chk_designation_level_rank_positive'),
    sa.ForeignKeyConstraint(['company_id'], ['company_master.company_id'], name='fk_designation_company_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('designation_id'),
    sa.UniqueConstraint('company_id', 'designation_code', name='uq_designation_company_code'),
    sa.UniqueConstraint('company_id', 'designation_name', name='uq_designation_company_name'),
    comment='Master registry for company-specific employee designations in Gocompliances CRM'
    )
    op.create_index(op.f('ix_designation_master_company_id'), 'designation_master', ['company_id'], unique=False)
    op.create_index(op.f('ix_designation_master_level_rank'), 'designation_master', ['level_rank'], unique=False)
    op.create_index(op.f('ix_designation_master_status'), 'designation_master', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_designation_master_status'), table_name='designation_master')
    op.drop_index(op.f('ix_designation_master_level_rank'), table_name='designation_master')
    op.drop_index(op.f('ix_designation_master_company_id'), table_name='designation_master')
    op.drop_table('designation_master')
    # ### end Alembic commands ###
