"""create_module_master

Revision ID: f46f50205034
Revises: 3295d9536783
Create Date: 2026-09-20 19:45:50.633572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f46f50205034'
down_revision: Union[str, None] = '3295d9536783'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_master',
    sa.Column('module_id', sa.UUID(), nullable=False, comment='Unique identifier for the module (UUIDv4)'),
    sa.Column('module_code', sa.String(length=60), nullable=False, comment='Uppercase unique system identifier (e.g., ADMIN, ADMIN_COMPANIES)'),
    sa.Column('module_name', sa.String(length=100), nullable=False, comment='Display name of the module (e.g., Admin, Companies, Sales)'),
    sa.Column('parent_module_id', sa.UUID(), nullable=True, comment='Nullable self-referencing foreign key to parent module (ON DELETE RESTRICT)'),
    sa.Column('route', sa.String(length=200), nullable=True, comment="Frontend route path starting with '/' (unique if provided)"),
    sa.Column('description', sa.String(length=500), nullable=True, comment='Optional description of module features'),
    sa.Column('display_order', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='Display sorting order (>= 0; lower value = higher priority)'),
    sa.Column('is_navigation', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Whether module should appear in UI navigation (does not grant permission)'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'ACTIVE'"), nullable=False, comment='Operational status: ACTIVE or INACTIVE'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when module record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when module record was last updated (UTC)'),
    sa.CheckConstraint("module_code ~ '^[A-Z_]+$'", name='chk_module_code_format'),
    sa.CheckConstraint("route IS NULL OR route ~ '^/'", name='chk_module_route_format'),
    sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE')", name='chk_module_status_valid'),
    sa.CheckConstraint('display_order >= 0', name='chk_module_display_order_non_negative'),
    sa.CheckConstraint('parent_module_id IS NULL OR parent_module_id <> module_id', name='chk_module_self_parent'),
    sa.ForeignKeyConstraint(['parent_module_id'], ['module_master.module_id'], name='fk_module_parent_module_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('module_id'),
    comment='Master registry for application modules, sub-modules and navigation hierarchy'
    )
    op.create_index(op.f('ix_module_master_display_order'), 'module_master', ['display_order'], unique=False)
    op.create_index(op.f('ix_module_master_module_code'), 'module_master', ['module_code'], unique=True)
    op.create_index(op.f('ix_module_master_parent_module_id'), 'module_master', ['parent_module_id'], unique=False)
    op.create_index(op.f('ix_module_master_route'), 'module_master', ['route'], unique=True)
    op.create_index(op.f('ix_module_master_status'), 'module_master', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_module_master_status'), table_name='module_master')
    op.drop_index(op.f('ix_module_master_route'), table_name='module_master')
    op.drop_index(op.f('ix_module_master_parent_module_id'), table_name='module_master')
    op.drop_index(op.f('ix_module_master_module_code'), table_name='module_master')
    op.drop_index(op.f('ix_module_master_display_order'), table_name='module_master')
    op.drop_table('module_master')
    # ### end Alembic commands ###
