"""Pydantic schemas package."""
from app.schemas.auth import (
    ChangePasswordRequest,
    CurrentUserRead,
    LoginRequest,
    LogoutRequest,
    RefreshTokenRequest,
    TokenResponse,
)
from app.schemas.company import (
    CompanyBase,
    CompanyCreate,
    CompanyRead,
    CompanyUpdate,
)
from app.schemas.department import (
    DepartmentBase,
    DepartmentCreate,
    DepartmentRead,
    DepartmentUpdate,
)
from app.schemas.designation import (
    DesignationBase,
    DesignationCreate,
    DesignationRead,
    DesignationUpdate,
)
from app.schemas.lookup import (
    CompanyLookupRead,
    DepartmentLookupRead,
    DesignationLookupRead,
    ManagerLookupRead,
)
from app.schemas.module import (
    ModuleBase,
    ModuleCreate,
    ModuleRead,
    ModuleTreeRead,
    ModuleUpdate,
)
from app.schemas.permission import (
    AccessibleModuleRead,
    CatalogModuleItem,
    CatalogPageItem,
    CopyPermissionsRequest,
    CopyPermissionsResponse,
    PageActionPermission,
    PermissionCatalogResponse,
    UserEffectivePermissionsResponse,
    UserModulePermissionBase,
    UserModulePermissionCreate,
    UserModulePermissionRead,
    UserModulePermissionUpdate,
    UserPermissionsDetailResponse,
    UserPermissionsSaveRequest,
    UserSettingsUpdate,
)
from app.schemas.user import (
    EmployeeRead,
    EmployeeStatusUpdate,
    PaginatedEmployeesResponse,
    UserBase,
    UserCreate,
    UserRead,
    UserUpdate,
)

__all__ = [
    "AccessibleModuleRead",
    "CatalogModuleItem",
    "CatalogPageItem",
    "ChangePasswordRequest",
    "CompanyBase",
    "CompanyCreate",
    "CompanyLookupRead",
    "CompanyRead",
    "CompanyUpdate",
    "CopyPermissionsRequest",
    "CopyPermissionsResponse",
    "CurrentUserRead",
    "DepartmentBase",
    "DepartmentCreate",
    "DepartmentLookupRead",
    "DepartmentRead",
    "DepartmentUpdate",
    "DesignationBase",
    "DesignationCreate",
    "DesignationLookupRead",
    "DesignationRead",
    "DesignationUpdate",
    "EmployeeRead",
    "EmployeeStatusUpdate",
    "LoginRequest",
    "LogoutRequest",
    "ManagerLookupRead",
    "ModuleBase",
    "ModuleCreate",
    "ModuleRead",
    "ModuleTreeRead",
    "ModuleUpdate",
    "PageActionPermission",
    "PaginatedEmployeesResponse",
    "PermissionCatalogResponse",
    "RefreshTokenRequest",
    "TokenResponse",
    "UserBase",
    "UserCreate",
    "UserEffectivePermissionsResponse",
    "UserModulePermissionBase",
    "UserModulePermissionCreate",
    "UserModulePermissionRead",
    "UserModulePermissionUpdate",
    "UserPermissionsDetailResponse",
    "UserPermissionsSaveRequest",
    "UserRead",
    "UserSettingsUpdate",
    "UserUpdate",
]
